server.port=8081

spring.data.mongodb.uri=mongodb+srv://aadish_assignment:assignment@assignment-cluster.ric3hrh.mongodb.net/rideshare?retryWrites=true&w=majority&appName=assignment-cluster

spring.jackson.serialization.write-dates-as-timestamps=false

# JWT
app.jwt.secret=ksajd82nbasdj82nasd8asdnasd87as8d7asd8a7sd8a7sd8a7sd8as7d8as7d8
app.jwt.expiration-ms=86400000
